const baseUrl = "http://localhost:8080"
const bookUrl = "/books?n="
const amountOfBooks = 15

// Fetch request generated by ChatGPT
async function getRandomBooks() {
    try {
      const response = await fetch(baseUrl + bookUrl + amountOfBooks);
      if (!response.ok) {
        throw new Error(`Response status: ${response.status}`);
      }
  
      const books = await response.json();
      displayBooks(books);
    } catch (error) {
      console.error(error.message);
    }
  }
  
  function displayBooks(books) {
    const bookList = document.getElementById("book-list");
  
    // Clear existing content
    bookList.innerHTML = "";
  
    // Add books to the list
    books.forEach((book) => {
      const listItem = document.createElement("li");
      listItem.textContent = book.title || "Untitled Book";
      bookList.appendChild(listItem);
    });
  }
  
  getRandomBooks();